server:
  port: 8089

spring:
  application.name: movie-cruiser-app
  data:
    mongodb:
      database: stackroute
      uri: mongodb://localhost:27017
logging:
  level:
    org.springframework.web: ERROR
    com.stackroute: DEBUG
    spring.data.mongodb: ERROR

  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
  path: logs
  file: ${logging.path}/movie_app.log

eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8871/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
